package org.redquark.techinterview.dsa.string;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Anirudh Sharma
 * <p>
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String,
 * that is generated by deleting some character of a given string without changing its order.
 */
public class AllSubsequences {

    private static List<String> findSubsequences(String s) {
        // List to store the result
        List<String> subsequences = new ArrayList<>();
        findSubsequences(s, "", subsequences);
        return subsequences;
    }

    private static void findSubsequences(String s, String current, List<String> subsequences) {
        // Base case
        if (s.isEmpty()) {
            subsequences.add(current);
            return;
        }
        // Include first character
        findSubsequences(s.substring(1), current + s.charAt(0), subsequences);
        // Skip first character
        findSubsequences(s.substring(1), current, subsequences);
    }

    public static void main(String[] args) {
        System.out.println(findSubsequences("Hello"));
        System.out.println(findSubsequences("abcd"));
    }
}
